/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './navigator.component.less.shim.ngstyle';
import * as i1 from '../../styles/main.less.shim.ngstyle';
import * as i2 from '@angular/core';
import * as i3 from '../../../../public_src/components/navigator/navigator.component';
import * as i4 from '@angular/forms';
import * as i5 from '../../../../public_src/services/geocoding.service';
import * as i6 from '../../../../public_src/services/map.service';
const styles_NavigatorComponent:any[] = [i0.styles,i1.styles];
export const RenderType_NavigatorComponent:i2.RendererType2 = i2.ɵcrt({encapsulation:0,
    styles:styles_NavigatorComponent,data:{}});
export function View_NavigatorComponent_0(_l:any):i2.ɵViewDefinition {
  return i2.ɵvid(0,[(_l()(),i2.ɵeld(0,0,(null as any),(null as any),5,'input',[['class',
      'on-map'],['id','place-input'],['placeholder','Enter a place to go...'],['type',
      'text']],[[2,'ng-untouched',(null as any)],[2,'ng-touched',(null as any)],[2,
      'ng-pristine',(null as any)],[2,'ng-dirty',(null as any)],[2,'ng-valid',(null as any)],
      [2,'ng-invalid',(null as any)],[2,'ng-pending',(null as any)]],[[(null as any),
      'ngModelChange'],[(null as any),'keyup.enter'],[(null as any),'input'],[(null as any),
      'blur'],[(null as any),'compositionstart'],[(null as any),'compositionend']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:i3.NavigatorComponent = _v.component;
        if (('input' === en)) {
          const pd_0:any = ((<any>i2.ɵnov(_v,1)._handleInput($event.target.value)) !== false);
          ad = (pd_0 && ad);
        }
        if (('blur' === en)) {
          const pd_1:any = ((<any>i2.ɵnov(_v,1).onTouched()) !== false);
          ad = (pd_1 && ad);
        }
        if (('compositionstart' === en)) {
          const pd_2:any = ((<any>i2.ɵnov(_v,1)._compositionStart()) !== false);
          ad = (pd_2 && ad);
        }
        if (('compositionend' === en)) {
          const pd_3:any = ((<any>i2.ɵnov(_v,1)._compositionEnd($event.target.value)) !== false);
          ad = (pd_3 && ad);
        }
        if (('ngModelChange' === en)) {
          const pd_4:any = ((<any>(_co.address = $event)) !== false);
          ad = (pd_4 && ad);
        }
        if (('keyup.enter' === en)) {
          const pd_5:any = ((<any>_co.goto()) !== false);
          ad = (pd_5 && ad);
        }
        return ad;
      },(null as any),(null as any))),i2.ɵdid(1,16384,(null as any),0,i4.DefaultValueAccessor,
      [i2.Renderer2,i2.ElementRef,[2,i4.COMPOSITION_BUFFER_MODE]],(null as any),(null as any)),
      i2.ɵprd(1024,(null as any),i4.NG_VALUE_ACCESSOR,(p0_0:any) => {
        return [p0_0];
      },[i4.DefaultValueAccessor]),i2.ɵdid(3,671744,(null as any),0,i4.NgModel,[[8,
          (null as any)],[8,(null as any)],[8,(null as any)],[2,i4.NG_VALUE_ACCESSOR]],
          {model:[0,'model']},{update:'ngModelChange'}),i2.ɵprd(2048,(null as any),
          i4.NgControl,(null as any),[i4.NgModel]),i2.ɵdid(5,16384,(null as any),0,
          i4.NgControlStatus,[i4.NgControl],(null as any),(null as any)),(_l()(),i2.ɵted(-1,
          (null as any),['\n\n '])),(_l()(),i2.ɵeld(7,0,(null as any),(null as any),
          3,'button',[['class','btn btn-primary on-map'],['href','#'],['id','goto'],
              ['title','Goto Place']],(null as any),[[(null as any),'click']],(_v,
              en,$event) => {
            var ad:boolean = true;
            var _co:i3.NavigatorComponent = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.goto()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i2.ɵted(-1,(null as any),['\n     '])),
      (_l()(),i2.ɵeld(9,0,(null as any),(null as any),1,'i',[['class','fa fa-arrow-right fa']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i2.ɵted(-1,(null as any),['\n '])),(_l()(),i2.ɵted(-1,(null as any),
          ['\n\n \n']))],(_ck,_v) => {
    var _co:i3.NavigatorComponent = _v.component;
    const currVal_7:any = _co.address;
    _ck(_v,3,0,currVal_7);
  },(_ck,_v) => {
    const currVal_0:any = i2.ɵnov(_v,5).ngClassUntouched;
    const currVal_1:any = i2.ɵnov(_v,5).ngClassTouched;
    const currVal_2:any = i2.ɵnov(_v,5).ngClassPristine;
    const currVal_3:any = i2.ɵnov(_v,5).ngClassDirty;
    const currVal_4:any = i2.ɵnov(_v,5).ngClassValid;
    const currVal_5:any = i2.ɵnov(_v,5).ngClassInvalid;
    const currVal_6:any = i2.ɵnov(_v,5).ngClassPending;
    _ck(_v,0,0,currVal_0,currVal_1,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6);
  });
}
export function View_NavigatorComponent_Host_0(_l:any):i2.ɵViewDefinition {
  return i2.ɵvid(0,[(_l()(),i2.ɵeld(0,0,(null as any),(null as any),1,'navigator',
      ([] as any[]),(null as any),(null as any),(null as any),View_NavigatorComponent_0,
      RenderType_NavigatorComponent)),i2.ɵdid(1,114688,(null as any),0,i3.NavigatorComponent,
      [i5.GeocodingService,i6.MapService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NavigatorComponentNgFactory:i2.ComponentFactory<i3.NavigatorComponent> = i2.ɵccf('navigator',
    i3.NavigatorComponent,View_NavigatorComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL25hdmlnYXRvci9uYXZpZ2F0b3IuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2Vwc2Vicm91L3B1YmxpY19zcmMvY29tcG9uZW50cy9uYXZpZ2F0b3IvbmF2aWdhdG9yLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L2Vwc2Vicm91L3B1YmxpY19zcmMvY29tcG9uZW50cy9uYXZpZ2F0b3IvbmF2aWdhdG9yLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL25hdmlnYXRvci9uYXZpZ2F0b3IuY29tcG9uZW50LnRzLk5hdmlnYXRvckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxpbnB1dCBpZD1cInBsYWNlLWlucHV0XCIgY2xhc3M9XCJvbi1tYXBcIiB0eXBlPVwidGV4dFwiIHBsYWNlaG9sZGVyPVwiRW50ZXIgYSBwbGFjZSB0byBnby4uLlwiXG4gWyhuZ01vZGVsKV09XCJhZGRyZXNzXCIgKGtleXVwLmVudGVyKT1cImdvdG8oKVwiPlxuXG4gPGJ1dHRvbiBpZD1cImdvdG9cIiBjbGFzcz1cImJ0biBidG4tcHJpbWFyeSBvbi1tYXBcIiBocmVmPVwiI1wiIHRpdGxlPVwiR290byBQbGFjZVwiIChjbGljayk9XCJnb3RvKClcIj5cbiAgICAgPGkgY2xhc3M9XCJmYSBmYS1hcnJvdy1yaWdodCBmYVwiPlxuIDwvaT48L2J1dHRvbj5cblxuIFxuIiwiPG5hdmlnYXRvcj48L25hdmlnYXRvcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQTtNQUFBO01BQUE7TUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO1VBQUE7UUFBQTtRQUFBO1VBQUE7VUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFDQztVQUFBO1VBQUE7UUFBQTtRQUFzQjtVQUFBO1VBQUE7UUFBQTtRQUR2QjtNQUFBLHVDQUFBO01BQUE7YUFBQTtRQUFBO01BQUEsb0NBQUE7VUFBQTtVQUFBLHFEQUFBO3VCQUFBLG1DQUFBOzZCQUFBLDRDQUM4QztVQUFBLDBCQUU3QztVQUFBO2NBQUE7dUJBQUE7WUFBQTtZQUFBO1lBQTZFO2NBQUE7Y0FBQTtZQUFBO1lBQTdFO1VBQUEsZ0NBQThGO01BQzFGO1VBQUE7TUFBZ0MsMkNBQ3ZCO1VBQUE7O0lBSmI7SUFERCxXQUNDLFNBREQ7O0lBQUE7SUFBQTtJQUFBO0lBQUE7SUFBQTtJQUFBO0lBQUE7SUFBQSxXQUFBLHFFQUFBOzs7O29CQ0FBO01BQUE7bUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
