/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../styles/main.less.shim.ngstyle';
export const styles:any[] = ['input[_ngcontent-%COMP%] {\n    margin: 20px 0 0 20px;\n    width: 300px;\n    height: 35px;\n    border: 2px solid rgba(77, 156, 237, 0.7);\n    font-size: 16px;\n    font: rgb(142, 142, 142);\n}\n\n\n#goto[_ngcontent-%COMP%] {\n    margin: 20px 0 0 330px;\n    .map-button\n}',
    i0.styles];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL25hdmlnYXRvci9uYXZpZ2F0b3IuY29tcG9uZW50Lmxlc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL25hdmlnYXRvci9uYXZpZ2F0b3IuY29tcG9uZW50Lmxlc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7In0=
