/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../public_src/app.module';
import * as i2 from '../../public_src/components/app/app.component';
import * as i3 from './components/app/app.component.ngfactory';
import * as i4 from '@angular/http';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/common';
import * as i7 from '@angular/platform-browser';
import * as i8 from '../../public_src/services/map.service';
import * as i9 from '../../public_src/services/geocoding.service';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i4.BrowserXhr,i4.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i4.ResponseOptions,
              i4.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i4.XSRFStrategy,i4.ɵb,
              ([] as any[])),i0.ɵmpd(4608,i4.XHRBackend,i4.XHRBackend,[i4.BrowserXhr,
              i4.ResponseOptions,i4.XSRFStrategy]),i0.ɵmpd(4608,i4.RequestOptions,
              i4.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i4.Http,i4.ɵc,[i4.XHRBackend,
              i4.RequestOptions]),i0.ɵmpd(4608,i5.ɵi,i5.ɵi,([] as any[])),i0.ɵmpd(5120,
              i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i6.NgLocalization,
              i6.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
              i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i7.DomSanitizer,i7.ɵe,[i6.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i7.DomSanitizer]),i0.ɵmpd(4608,
              i7.HAMMER_GESTURE_CONFIG,i7.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i7.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i7.ɵDomEventsPlugin(p0_0),new i7.ɵKeyEventsPlugin(p1_0),
                    new i7.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i6.DOCUMENT,i6.DOCUMENT,i6.DOCUMENT,i7.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i7.EventManager,i7.EventManager,[i7.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i7.ɵDomSharedStylesHost,i7.ɵDomSharedStylesHost,[i6.DOCUMENT]),
          i0.ɵmpd(4608,i7.ɵDomRendererFactory2,i7.ɵDomRendererFactory2,[i7.EventManager,
              i7.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i7.ɵDomRendererFactory2]),i0.ɵmpd(6144,i7.ɵSharedStylesHost,(null as any),
              [i7.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i7.Meta,i7.Meta,[i6.DOCUMENT]),i0.ɵmpd(4608,
              i7.Title,i7.Title,[i6.DOCUMENT]),i0.ɵmpd(4608,i8.MapService,i8.MapService,
              [i4.Http]),i0.ɵmpd(4608,i9.GeocodingService,i9.GeocodingService,[i4.Http]),
          i0.ɵmpd(512,i4.HttpModule,i4.HttpModule,([] as any[])),i0.ɵmpd(512,i5.ɵba,
              i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.FormsModule,i5.FormsModule,([] as any[])),
          i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i7.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any) => {
                return [i7.ɵc(p0_0,p0_1)];
              },[[2,i7.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i7.BrowserModule,i7.BrowserModule,[[3,i7.BrowserModule]]),i0.ɵmpd(512,
              i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZXBzZWJyb3UvcHVibGljX3NyYy9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2Vwc2Vicm91L3B1YmxpY19zcmMvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
