/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../styles/main.less.shim.ngstyle';
export const styles:any[] = ['#add-marker[_ngcontent-%COMP%] {\n    margin: 20px 0 0 370px;\n    .map-button;\n}\n\n#remove-marker[_ngcontent-%COMP%] {\n    margin: 20px 0 0 410px;\n    .map-button;\n}\n\n#toggle-layer[_ngcontent-%COMP%] {\n    margin: 20px 0 0 450px;\n    .map-button;\n}\n#postPanel[_ngcontent-%COMP%] {  \n    width: 300px;\n    height: 100px;\n    border: 2px solid rgba(77, 156, 237, 0.7);\n    font-size: 16px;\n    font: rgb(142, 142, 142);\n}\n#userPanel[_ngcontent-%COMP%]{\n    width: 300px;\n    height: 100px;\n    border: 2px solid rgba(77, 156, 237, 0.7);\n    margin-top:60px;\n    font-size: 16px;\n    font: rgb(142, 142, 142);\n}\n#commentsPanel[_ngcontent-%COMP%]{\n    width: 300px;\n    height: 100px;\n    border: 2px solid rgba(77, 156, 237, 0.7);\n    font-size: 16px;\n    font: rgb(142, 142, 142);\n}\n#photosPanel[_ngcontent-%COMP%]{\n        width: 300px;\n        height: 100px;\n        border: 2px solid rgba(77, 156, 237, 0.7);\n        font-size: 16px;\n        float: right;;\n        font: rgb(142, 142, 142); \n}',
    i0.styles];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL3Rvb2xiYXIvdG9vbGJhci5jb21wb25lbnQubGVzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9lcHNlYnJvdS9wdWJsaWNfc3JjL2NvbXBvbmVudHMvdG9vbGJhci90b29sYmFyLmNvbXBvbmVudC5sZXNzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7OyJ9
