/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.on-map[_ngcontent-%COMP%] {\n    position: absolute;\n    z-index: 1000;\n}\n\n.map-button[_ngcontent-%COMP%] {\n    width: 35px;\n    height: 35px;\n    text-align: center;\n}\n\n\n.leaflet-clickable[_ngcontent-%COMP%] {\n  cursor: crosshair !important;\n}\n\n.leaflet-container[_ngcontent-%COMP%] {\n  cursor: help !important;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZXBzZWJyb3UvcHVibGljX3NyYy9zdHlsZXMvbWFpbi5sZXNzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2Vwc2Vicm91L3B1YmxpY19zcmMvc3R5bGVzL21haW4ubGVzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
