/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['body[_ngcontent-%COMP%] {\n    margin:0;\n    padding:0;\n}\n\n#map[_ngcontent-%COMP%] {\n    position:absolute;\n    top:50px;\n    bottom:0;\n    width:100%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL2FwcC9hcHAuY29tcG9uZW50Lmxlc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovZXBzZWJyb3UvcHVibGljX3NyYy9jb21wb25lbnRzL2FwcC9hcHAuY29tcG9uZW50Lmxlc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
